### ISSUE TITLE
Allow it to be visible from start

### ISSUE THREAD

**Issue by robertherber** [sidevesh/react-native-snackbar-component#1]
Right now it's not showing if visible is set to true on mount, it would be great if it would.

**Comment by sidevesh** [comment]
Thanks for the feedback! Gonna look into it...

**Comment by Taakn** [comment]
That would be fantastic thanks

**Comment by sidevesh** [comment]
Fixed the issue! It should be visible from start now if visible prop is true...

**Comment by Taakn** [comment]
@SiDevesh Fantastic, thanks a lot for fixing this !
