### ISSUE TITLE
How to dismiss the snackbar

### ISSUE THREAD

**Issue by jamesangetonhouse** [sidevesh/react-native-snackbar-component#18]
I notice there is no sample code to dismiss the snackbar. Wondering how to do it?

**Comment by efstathiosntonas** [comment]
Late to the party, but if someone else lands here:

When you set it to `visible: true` you need to setTimeout, in the case below it will go away after 3 seconds.

```
this.setState({visible: true}, () => {
                        setTimeout(()=> {
                            this.setState({visible: false})
                        }, 3000)
                    })
```
