### ISSUE TITLE
Use icon instead of action text

### ISSUE THREAD

**Issue by PiotrSzlagura** [sidevesh/react-native-snackbar-component#26]
Is there any way I could add Icon instead of text in snackbar action?

Something like:

```
 <SnackBar
    visible={true}
    textMessage={"Snackbar text"}
    actionLabel={<Icon name="icon" size={30} />}
    // ...rest
  />
```

**Comment by sidevesh** [comment]
Hey @PiotrSzlagura ,
Sorry for delay, pushed an update implementing this.
You can pass any custom JSX to `textMessage` to render something custom.
Do open the PR again if that doesn't solve it.
