### ISSUE TITLE
refactor class component 

### ISSUE THREAD

**Issue by serusko** [sidevesh/react-native-snackbar-component#40]
its would be nice if we can get rid of those yellowBox warnings:

`Warning: componentWillReceiveProps`
https://github.com/SiDevesh/React-Native-SnackBar-Component/blob/b4b836994b84108f72d472457f23dfa02a91e750/index.js#L94
`Warning: componentWillUpdate`
https://github.com/SiDevesh/React-Native-SnackBar-Component/blob/b4b836994b84108f72d472457f23dfa02a91e750/index.js#L110

so maybe there is required refactor to react hooks api

**Comment by serusko** [comment]
PR waiting for review 

https://github.com/SiDevesh/React-Native-SnackBar-Component/pull/41

**Comment by sidevesh** [comment]
Closing this to continue discussion on the PR
