### ISSUE TITLE
Add useNativeDriver: true to Animation.timer

### ISSUE THREAD

**Issue by kanyo33** [sidevesh/react-native-snackbar-component#47]
Small reminder when you get around to updating the package. Thanks.

**Comment by shubhamkakkar** [comment]
@kanyo33 hey, I have raised a PR for the same, it was an easy thing, looking forward to merge.
Thanks for raising a ticket

**Comment by willmontiel** [comment]
Hi, a couple of months have passed. Anyone knows about this change? ty

**Comment by sfustar** [comment]
> Hi, a couple of months have passed. Anyone knows about this change? ty

I forked and fixed the error.
https://github.com/icebergMNE/react-native-snackbar-component
