### ISSUE TITLE
Cannot read property 'func' of undefined

### ISSUE THREAD

**Issue by eduardoperez2151** [sidevesh/react-native-snackbar-component#5]
![f30db704-0784-4017-b7fa-b65515af9d2f](https://user-images.githubusercontent.com/7648623/31828818-ca88075c-b591-11e7-973a-f19c65e7418e.jpg)

Any idea about this issue?

**Comment by TimoGlastra** [comment]
it is because the old version is using the built in Proptypes that was removed in react 16. This repo is already updated, but the npm version is not. So you will have to download it via this repo.

**Comment by sidevesh** [comment]
I have updated the npm package. Let me know if the issue isn't resolved.

**Comment by eduardoperez2151** [comment]
Hi,SiDevesh the package update works fine, now it is working.
Thanks!!!
