### ISSUE TITLE
not able to change the fontSize, i would appreciate any fix, thanks in advance

### ISSUE THREAD

**Issue by rajesh221b** [sidevesh/react-native-snackbar-component#52]
not able to overide fontsize with messageStyle prop, i would appreciate any fix, thanks in advance

**Comment by sidevesh** [comment]
Hey @rajesh221b , If you look at https://github.com/sidevesh/react-native-snackbar-component/blob/7b0875668a45ac0af106506af72ae8f1355f437d/index.js#L212 fontSize is one of the properties that can't be overriden by the messageStyle prop, you can supply your own render method to `textMessage` to get better control over this.
