### ISSUE TITLE
Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`

### ISSUE THREAD

**Issue by devtyty** [sidevesh/react-native-snackbar-component#57]
I use the latest version and still have this problem.  1.1.11

**Comment by rpattcorner** [comment]
From what I can tell, this repository isn't being actively maintained.  But there are a couple forks that claim to have fixed the problem.  Or you can hide the warning, as documented.

**Comment by r1jsheth** [comment]
Can I work on this? @sidevesh

**Comment by sidevesh** [comment]
Last when I was working with this library, `useNativeDriver` used to be not required and not even well supported even by react native's own components, clearly things have changed now.
Unfortunately I haven't used this library in a while (or worked in react native actually for some time),
would be great if someone can take over maintaining this library.
@rhetoricalraj sure, feel free to open a PR.

**Comment by r1jsheth** [comment]
Thanks!

**Comment by r1jsheth** [comment]
Raised this PR #69

**Comment by sidevesh** [comment]
Closing this issue, useNativeDriver is now specified as false, last I tested setting it to true broke the animation,
if that is not the case anymore, feel free to open another issue and we can set it to true
