### ISSUE TITLE
AutoHidingTime (autoHide) does not properly reset component visibility

### ISSUE THREAD

**Issue by rpattcorner** [sidevesh/react-native-snackbar-component#58]
I think this repository may be unmaintained, but am posting in hope of some thoughts from consumers.  This (and its forks) appear to be the only viable expo-friendly snackbars as of this date.  

It looks to me like the component does not properly set its visibility state after an autohide as triggered by AutoHidingTime.  Here's my use case:

* Let's have a reproducible error, say adding an item to a screen where duplicates are not allowed
* Detect the duplicate, fill in the message, set visible to true and snackbar shows the message
* Add the same (or different) duplicate a second time, set snackbar component visible to true and snackbar still shows the proper message

Now ...

* Turn on autohiding with a reasonable value (say 3000)
* Add the initial duplicate, see the correct snackbar
* Subsequent duplicate adds (same or different duplicate item) do *not* display the snackbar

Adding some debugging shows that the component that encloses the snackbar is properly setting the visibility to TRUE in each duplicate case.  The problem appears to be that the snackbar, after autohiding, still thinks that its visibility is TRUE, after autotime has hidden the snackbar, when in fact it is not visible.  It looks like the snackbar sees the second duplicate addition as a no-op since the snackbar already thinks it is visible, although in fact it is not, because the autotime has hidden the snackbar.

Provable by adding a button that toggles visibility .. if between the two duplicate runs you use the button to reset visibility to FALSE (corresponding to the true state of the component), the next duplicate run succeeds.

What should *probably* happen -- doing this is above my pay grade -- is that the piece of code that runs when the timer autohides should also set visibility on the component to FALSE, since it just disappeared.

There's a cryptic bit in the README that says:

`The snackbar will not auto-dismiss by itself, for auto-dismiss use setTimeout() and change value passed to prop to false`

This might be relevant, if anyone might explain ...
* Clearly the snackbar auto-dismisses just fine by itself with autoHide, so something different might be meant
* There's no setTimeout() function or parm available that I can see

Thoughts most welcome

**Comment by sidevesh** [comment]
`visible` will need to be set to false after the `autoHidingTime` hides it, I agree its a bit confusing, will update the docs.

**Comment by sidevesh** [comment]
Updated the README
