### ISSUE TITLE
QUESTION: Nested Animated.View

### ISSUE THREAD

**Issue by louisiscoding** [sidevesh/react-native-snackbar-component#9]
Hi,

First of all, thanks for this component. It is really useful and well-made.
By digging deeper in the code, i've noticed you're nesting two Animated.View (index.js).

I wonder why you did it this way. As far as i understand, you're using one for 'hiding' animation and the other one for 'showing' animation.
Wouldn't it be possible to do both of these animation with only one Animated.View ?

Thanks, Louis.
[You can label this issue with a 'Questions' label]

**Comment by sidevesh** [comment]
HI, It most certainly is!. I started using Animated API while making this library, there definitely is room for improvement here in the approached I have taken. Feel free to create a PR if you can improve this.
